name: PR Agent
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  push:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: "Run pr agent on every pull request, respond to user comments"
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Authenticate to Google Cloud"
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }} # 出力値を登録
          service_account: ${{ secrets.GCP_SA_EMAIL }} # 出力値を登録

      - name: "gcloud info"
        run: gcloud info

      # - name: "PR Agent action step"
      #   id: pragent
      #   uses: qodo-ai/pr-agent@main
      #   env:
      #     OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     vertexai.vertex_project: ${{ secrets.VERTEX_PROJECT }}
      #     vertexai.vertex_location: ""
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
