name: PR Agent
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      issues: write
      pull-requests: write
      contents: write
      id-token: write
    name: "Run pr agent on every pull request, respond to user comments"
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Authenticate to Google Cloud"
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }} # 出力値を登録
          service_account: ${{ vars.GCP_SA_EMAIL }} # 出力値を登録

      - name: "gcloud info"
        run: gcloud info

      - name: "PR Agent action step"
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
